-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 19:00:02 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema blog_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog_api` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `blog_api` ;

-- -----------------------------------------------------
-- Table `blog_api`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`categories` (
  `c_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`c_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_live` BIT(1) NOT NULL,
  `about` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_6dotkott2kjsp8vw4d0m25fb7` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`posts` (
  `category_id` INT NOT NULL,
  `is_live` BIT(1) NOT NULL,
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date_added` DATETIME(6) NULL DEFAULT NULL,
  `content` LONGTEXT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `FKijnwr3brs8vaosl80jg9rp7uc` (`category_id` ASC) VISIBLE,
  INDEX `FK5lidm6cqbc7u4xhqpxm898qme` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK5lidm6cqbc7u4xhqpxm898qme`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog_api`.`users` (`id`),
  CONSTRAINT `FKijnwr3brs8vaosl80jg9rp7uc`
    FOREIGN KEY (`category_id`)
    REFERENCES `blog_api`.`categories` (`c_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `content` LONGTEXT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `FKh4c7lvsc298whoyd4w9ta25cr` (`post_id` ASC) VISIBLE,
  INDEX `FK8omq0tc18jd43bu5tjh6jvraq` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK8omq0tc18jd43bu5tjh6jvraq`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog_api`.`users` (`id`),
  CONSTRAINT `FKh4c7lvsc298whoyd4w9ta25cr`
    FOREIGN KEY (`post_id`)
    REFERENCES `blog_api`.`posts` (`p_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`post_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`post_images` (
  `p_id` INT NOT NULL,
  `keys_image` VARCHAR(255) NOT NULL,
  `values_image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`p_id`, `keys_image`),
  CONSTRAINT `FK2a2cvsossgu5w1slkcnw3uv6j`
    FOREIGN KEY (`p_id`)
    REFERENCES `blog_api`.`posts` (`p_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`refresh_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`refresh_tokens` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `expiry` DATETIME(6) NULL DEFAULT NULL,
  `refresh_token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`token_id`),
  UNIQUE INDEX `UK_7tdcd6ab5wsgoudnvj7xf1b7l` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK1lih5y2npsf8u5o3vhdb9y0os`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog_api`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`user_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`user_images` (
  `id` INT NOT NULL,
  `keys_image` VARCHAR(255) NOT NULL,
  `values_image` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `keys_image`),
  CONSTRAINT `FKs23lcysun1im7mnamox1886hy`
    FOREIGN KEY (`id`)
    REFERENCES `blog_api`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `blog_api`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_api`.`user_role` (
  `role` INT NOT NULL,
  `user` INT NOT NULL,
  PRIMARY KEY (`role`, `user`),
  INDEX `FKlduspqw8rg0gbcpludbfadw6l` (`user` ASC) VISIBLE,
  CONSTRAINT `FK26f1qdx6r8j1ggkgras9nrc1d`
    FOREIGN KEY (`role`)
    REFERENCES `blog_api`.`role` (`id`),
  CONSTRAINT `FKlduspqw8rg0gbcpludbfadw6l`
    FOREIGN KEY (`user`)
    REFERENCES `blog_api`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
